export * from "./GameBackground"
export * from "./GlobalStyles"
export * from "./StyledGun"
export * from "./HPBar"
export * from "./StyledScore"
export * from "./StartButton"
export * from "./StyledDuck"
